import { defineConfig } from "vite-plus";

export default defineConfig({
  staged: {
    "*": "vp check --fix",
  },
  fmt: {
    printWidth: 80,
    sortImports: true,
  },
  lint: {
    options: { typeAware: true, typeCheck: true },
    jsPlugins: [{ name: "vite-plus", specifier: "vite-plus/oxlint-plugin" }],
    plugins: ["react", "typescript"],
    env: {
      browser: true,
    },
    categories: {
      correctness: "error",
      suspicious: "error",
      nursery: "error",
      restriction: "error",
      style: "error",
      pedantic: "error",
      perf: "error",
    },
    rules: {
      "vite-plus/prefer-vite-plus-imports": "error",
      "react/forbid-component-props": "off",
      "react/jsx-filename-extension": "off",
      "react/no-multi-comp": "off",
      "react/only-export-components": "off",
      "react/react-in-jsx-scope": "off",
      complexity: "off",
      "no-console": "error",
      "no-plusplus": "off",
      "no-undefined": "off",
      "no-use-before-define": "off",
      "no-void": "off",
      "capitalized-comments": "off",
      "func-style": "off",
      "init-declarations": "off",
      "max-statements": "off",
      "new-cap": "off",
      "no-magic-numbers": "off",
      "no-ternary": "off",
      "prefer-destructuring": "off",
      "sort-keys": "off",
      "sort-imports": "off",
      "react/jsx-max-depth": "off",
      "no-negated-condition": "off",
      "max-classes-per-file": "off",
      "max-lines": "off",
      "max-lines-per-function": "off",
      "no-promise-executor-return": "off",
      "require-await": "off",
      "require-unicode-regexp": "off",
      "typescript/explicit-function-return-type": "off",
      "typescript/explicit-member-accessibility": "off",
      "typescript/explicit-module-boundary-types": "off",
      "typescript/no-unnecessary-condition": "off",
      "typescript/prefer-readonly-parameter-types": "off",
      "typescript/strict-boolean-expressions": "off",
      "typescript/strict-void-return": "off",
      "typescript/unified-signatures": "off",

      // TMP
      "no-unsafe-type-assertion": "off",
      "no-unsafe-member-access": "off",
      "no-non-null-assertion": "off",
    },
    overrides: [
      {
        files: ["apps/app/src/lib/logger.ts"],
        rules: { "no-console": "off" },
      },
      {
        files: ["packages/**/*.ts"],
        rules: { "no-console": "off" },
      },
    ],
  },
  run: {
    cache: true,
  },
});
